### ISSUE TITLE
代码问题请教

### ISSUE THREAD

**Issue by cyndixxxxx** [HuangJunJie2017/UDP-Pose#3]
您好，在deep-high-resolution-net.pytorch/lib/utils/transforms.py中，第四十一行output_flipped = output_flipped.reshape(shape_ori[0],-1,3,shape_ori[2],shape_ori[3]) 运行报错，因为coco数据集应该是[64,17,64,48], 但reshape的17无法被3整除，这个要如何解决呢？
感谢回复！

**Comment by HuangJunJie2017** [comment]
> 您好，在deep-high-resolution-net.pytorch/lib/utils/transforms.py中，第四十一行output_flipped = output_flipped.reshape(shape_ori[0],-1,3,shape_ori[2],shape_ori[3]) 运行报错，因为coco数据集应该是[64,17,64,48], 但reshape的17无法被3整除，这个要如何解决呢？
> 感谢回复！

if you use the combined target, the output channels of network should be 51, i.e. shape=(64,51,64,48), 17 channels for heatmap and 34 channels for offsetmap
otherwise if you use gaussian heatmap for target, the output channels of network is 17, and then, you should use API 'flip_back' instead of 'flip_back_offset'
you can figure out how the algorithm discriminate these two situations by referring line 157-162 in "UDP-Pose/deep-high-resolution-net.pytorch/lib/core/function.py"

**Comment by HuangJunJie2017** [comment]
@cyndixxxxx  
if you use the combined target, the output channels of network should be 51, i.e. shape=(64,51,64,48), 17 channels for heatmap and 34 channels for offsetmap
otherwise if you use gaussian heatmap for target, the output channels of network is 17, and then, you should use API 'flip_back' instead of 'flip_back_offset'
you can figure out how the algorithm discriminate these two situations by referring line 157-162 in "UDP-Pose/deep-high-resolution-net.pytorch/lib/core/function.py"

**Comment by cyndixxxxx** [comment]
How to generate the output to be shape=(64,51,64,48)?  .yml file is filled with ‘offset’

**Comment by HuangJunJie2017** [comment]
@cyndixxxxx just use the default TARGET_TYPE('offset') as in default .yml ( UDP-Pose/deep-high-resolution-net.pytorch/experiments/coco/hrnet/w32_256x192_adam_lr1e-3_offset_ofm.yaml )

**Comment by cyndixxxxx** [comment]
Thank you for your reply
